global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "corporate-api"
    static_configs:
      - targets: ["corporate-api:6000"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "sqlserver"
    static_configs:
      - targets: ["sqlserver:1433"]

  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:16686"]
