FROM python:3.9-slim

WORKDIR /app

# Копируем requirements.txt
COPY requirements.txt .
RUN pip install -r requirements.txt

# Копируем приложение
COPY app.py .
COPY templates/ templates/

EXPOSE 8080

CMD ["python", "app.py"] 