groups:
  - name: corporate-portal-alerts
    rules:
      - alert: HighResponseTime
        expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "p99 response time is {{ $value }}s"

      - alert: HighDatabaseRPS
        expr: rate(sqlserver_requests_total[5m]) > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High database load detected"
          description: "Database RPS is {{ $value }}"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }}%"
