global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "corporate-portal-api"
    static_configs:
      - targets: ["host.docker.internal:5000"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "sqlserver"
    static_configs:
      - targets: ["host.docker.internal:1433"]
    scrape_interval: 10s
