apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    uid: jaeger
    isDefault: false
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
